name: Build, Scan & Deploy Docker Image

on:
  pull_request:
    branches:
      - dev
      - staging
      - main
    paths:
      - "app/**"

env:
  AWS_REGION: eu-west-2
  S3_BUCKET: codedeploy-artifacts-ecs
  APPSPEC_FILE: codedeploy/appspec.yml

permissions:
  id-token: write
  contents: read

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.build.outputs.image }}
      env_name: ${{ steps.set-env.outputs.env_name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Detect Environment
        id: set-env
        run: |
          BRANCH="${GITHUB_BASE_REF:-${GITHUB_REF##*/}}"

          if [ "$BRANCH" = "dev" ]; then
            echo "ENV=dev" >> $GITHUB_ENV
            echo "ROLE=${{ secrets.AWS_ROLE_DEV }}" >> $GITHUB_ENV
            echo "REPO=${{ secrets.ECR_REPO_DEV }}" >> $GITHUB_ENV
            echo "env_name=dev" >> $GITHUB_OUTPUT

          elif [ "$BRANCH" = "staging" ]; then
            echo "ENV=staging" >> $GITHUB_ENV
            echo "ROLE=${{ secrets.AWS_ROLE_STAGING }}" >> $GITHUB_ENV
            echo "REPO=${{ secrets.ECR_REPO_STAGING }}" >> $GITHUB_ENV
            echo "env_name=staging" >> $GITHUB_OUTPUT

          else
            echo "ENV=prod" >> $GITHUB_ENV
            echo "ROLE=${{ secrets.AWS_ROLE_PROD }}" >> $GITHUB_ENV
            echo "REPO=${{ secrets.ECR_REPO_PROD }}" >> $GITHUB_ENV
            echo "env_name=prod" >> $GITHUB_OUTPUT
          fi

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build & Push Docker Image
        id: build
        run: |
          TAG="${ENV}-${GITHUB_SHA}"
          IMAGE="${REPO}:${TAG}"

          docker build -t $IMAGE -f app/Dockerfile app/
          docker push $IMAGE

          echo "image=$IMAGE" >> $GITHUB_OUTPUT

      - name: Scan Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.build.outputs.image }}
          format: table
          severity: CRITICAL
          exit-code: 1
          ignore-unfixed: true


  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Environment
        run: |
          ENV="${{ needs.build-and-push.outputs.env_name }}"
          echo "ENV=$ENV" >> $GITHUB_ENV

          if [ "$ENV" = "dev" ]; then
            echo "ROLE=${{ secrets.AWS_ROLE_DEV }}" >> $GITHUB_ENV
          elif [ "$ENV" = "staging" ]; then
            echo "ROLE=${{ secrets.AWS_ROLE_STAGING }}" >> $GITHUB_ENV
          else
            echo "ROLE=${{ secrets.AWS_ROLE_PROD }}" >> $GITHUB_ENV
          fi

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Register ECS Task Definition
        run: |
          IMAGE="${{ needs.build-and-push.outputs.image }}"

          echo "Using image: $IMAGE"

          if [ -z "$IMAGE" ]; then
            echo "Image variable is empty"
            exit 1
          fi

          cat > task-def.json <<EOF
          {
            "family": "url-short-$ENV",
            "networkMode": "awsvpc",
            "requiresCompatibilities": ["FARGATE"],
            "cpu": "256",
            "memory": "512",
            "executionRoleArn": "${{ secrets.ECS_EXECUTION_ROLE }}",
            "containerDefinitions": [
              {
                "name": "urlshort",
                "image": "$IMAGE",
                "essential": true,
                "portMappings": [
                  {
                    "containerPort": 8080,
                    "protocol": "tcp"
                  }
                ]
              }
            ]
          }
          EOF

          TASK_ARN=$(aws ecs register-task-definition \
            --cli-input-json file://task-def.json \
            --query 'taskDefinition.taskDefinitionArn' \
            --output text)

          echo "TASK_DEF_ARN=$TASK_ARN" >> $GITHUB_ENV

      - name: Inject Task ARN into AppSpec
        run: |
          sed -i "s|<TASK_DEFINITION_ARN>|${TASK_DEF_ARN}|g" ${{ env.APPSPEC_FILE }}

      - name: Upload AppSpec to S3
        run: |
          aws s3 cp ${{ env.APPSPEC_FILE }} s3://${{ env.S3_BUCKET }}/appspec-${ENV}.yml

      - name: Trigger CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name url-shortener-${ENV} \
            --deployment-group-name blue-green-${ENV} \
            --s3-location bucket=${{ env.S3_BUCKET }},key=appspec-${ENV}.yml,bundleType=yaml