name: Terraform Apply - Staging

on:
  workflow_dispatch:

jobs:
  terraform-apply:
    name: Terraform Apply - Staging
    runs-on: ubuntu-latest

    environment: staging

    permissions:
      contents: read
      id-token: write

    concurrency:
      group: terraform-staging
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_STAGING }}
          aws-region: eu-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.14.0

      - name: Terraform Init
        working-directory: terraform/env/staging
        run: terraform init

      - name: Terraform Apply
        working-directory: terraform/env/staging
        run: |
          terraform apply -auto-approve \
            -var="container_name=urlshort" \
            -var="container_port=8080" \
            -var="task_cpu=256" \
            -var="task_memory=512" \
            -var="aws_region=eu-west-2" \
            -var="container_image=${{ secrets.ECR_REPO_STAGING }}" \
            -var="route53_zone_id=${{ secrets.ROUTE53_ZONE_ID }}"